# fly.toml app configuration file generated for email-poc on 2025-08-06T10:40:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'email-poc'
primary_region = 'jnb'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = "bin/rails db:prepare"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  LOG_LEVEL = 'debug'
  RAILS_ENV = 'production'